name: Forgejo CI Testing
on: [push]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: code.sbclab.net/elykseer/nixos:1.0.0
      options: >-
        --privileged
        --security-opt seccomp=unconfined
      credentials:
        username: ci_elykseer
        password: ${{ secrets.PAT }}
      env:
        DOCKER_TLS_CERTDIR: ""

    steps:
      - name: intro
        run: |
          echo "🎉 The job was automatically triggered by a ${{ forgejo.event_name }} event.";
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by forgejo!";
          echo "🔎 The name of your branch is ${{ forgejo.ref }} and your repository is ${{ forgejo.repository }}.";
      - name: install node
        run: nix-env -iA nixpkgs.nodejs_20
      - name: Check out repository code
        uses: https://data.forgejo.org/actions/checkout@v4
        with:
          submodules: false
          # token: ${{ secrets.PAT }}
      - run: |
          git submodule update --init
      - name: compute dependencies cache hash
        id: cache_hash
        shell: bash
        run: |
          HASH=$(sha256sum <(git submodule | cut -d ' ' -f 2) | cut -d ' ' -f 1)
          echo "hash=$HASH" >> $GITHUB_OUTPUT
          echo "output: hash=$HASH"
      - name: cache dependencies
        id: caching
        uses: actions/cache@v4
        with:
          key: ${{ steps.cache_hash.outputs.hash }}
          path: |
            ext/Linux_*
            ext/Darwin_*
            ext/xWindows_*
      - name: compile dependencies
        run: |
          nix-shell --run "make -C ext"
      - name: build project with OpenSSL
        shell: nix-shell --run "{0}"
        run: |
          mkdir -vp build
          cd build
          cmake --fresh -G Ninja -DUSE_OPENSSL=ON -DCMAKE_BUILD_TYPE=Debug ..
          ninja
      - name: test project (OpenSSL)
        shell: nix-shell --run "{0}"
        run: |
          cd build
          ./test/cpp/utelykseer-crypto --report_level=detailed
      - name: build and test project with Crypto++
        shell: nix-shell --run "{0}"
        run: |
          mkdir -vp build
          cd build
          ninja clean
          cmake --fresh -G Ninja -DUSE_CRYPTOPP=ON -DCMAKE_BUILD_TYPE=Debug ..
          ninja
          ./test/cpp/utelykseer-crypto --report_level=detailed || echo "some error occured"
      - run: echo "🍏 This job's status is ${{ job.status }}."
