name: Compilation of project with submodules and verification by unit tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  #PKG_CONFIG_PATH: ${{github.workspace}}/ext/linux/lib/pkgconfig:${PKG_CONFIG_PATH}

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    env:
      CC: clang-19
      CXX: clang++-19

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get -y install cmake ninja-build clang-19 clang-tools-19 swig opam m4 busybox openssl libssl-dev libdigest-sha3-perl libboost-all-dev libboost-contract-dev gettext pkg-config automake autoconf libtool
        gpg --keyserver hkp://keyserver.ubuntu.com --recv E2DFCA9AA83BA568AF39280999283F5327C5D38F

    - name: Update submodules
      shell: bash
      working-directory: ${{github.workspace}}/
      run: |
        mkdir -vp build
        git submodule update --init

    - name: compute dependencies cache hash
      id: cache_hash
      shell: bash
      run: |
        HASH=$(sha256sum <(git submodule | cut -d ' ' -f 2) | cut -d ' ' -f 1)
        echo "hash=$HASH" >> $GITHUB_OUTPUT
        echo "output: hash=$HASH"
    - name: cache dependencies
      id: caching
      uses: actions/cache@v4
      with:
        key: ${{ steps.cache_hash.outputs.hash }}
        path: |
          ext/Linux_*
          ext/Darwin_*
          ext/xWindows_*

    - name: Build dependencies
      shell: bash
      working-directory: ${{github.workspace}}/ext
      run: make

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake --fresh -GNinja -DUSE_OPENSSL=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest -C $BUILD_TYPE
      run: ./test/cpp/utelykseer-crypto --report_level=detailed

    - name: Build and test with Crypto++
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake --fresh -GNinja -DUSE_OPENSSL=OFF -DUSE_CRYPTOPP=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        cmake --build . --config $BUILD_TYPE
        ./test/cpp/utelykseer-crypto --report_level=detailed

    - name: Packaging
      shell: bash
      working-directory: ${{github.workspace}}/build
      run:  cpack
