name: Compilation of project with submodules and verification by unit tests
on:
  push:
    branches:
      - main

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get -y install git cmake pandoc libdigest-sha3-perl libboost-all-dev libboost-contract-dev libgpg-error-dev libassuan-dev libgpgme-dev swig gcc clang opam m4 busybox gnupg
          gpg --keyserver hkp://keyserver.ubuntu.com --recv E2DFCA9AA83BA568AF39280999283F5327C5D38F
          git clone https://github.com/grobian/html2text.git html2text.git
          cd html2text.git
          ./configure && make
          mkdir ~/bin/
          cp html2text ~/bin/
          echo "export PATH=\${HOME}/bin:\$PATH" >> ~/.bashrc

      - name: Update submodules
        run: git submodule update --init

      - name: Build dependencies
        shell: bash
        working-directory: ${{github.workspace}}/ext
        run: |
          cd cryptopp
          make -f GNUmakefile
          mkdir ../linux
          PREFIX="../linux" make install
          cd ../libgpg-error
          ./autogen.sh; ./configure --enable-static --disable-shared  --disable-doc --enable-install-gpg-error-config --prefix=$(pwd)/../linux
          make && make install
          cd ../libassuan
          ./autogen.sh; ./configure --enable-static --disable-shared  --disable-doc --prefix=$(pwd)/../linux
          make && make install
          cd ../gpgme
          ./autogen.sh; ./configure --enable-static --disable-shared --enable-languages=cpp --disable-gpgsm-test --disable-g13-test --disable-gpg-test --disable-gpgconf-test --with-libassuan-prefix=$(pwd)/../linux  --with-libgpg-error-prefix=$(pwd)/../linux  --prefix=$(pwd)/../linux
          make && make install
          ls ../linux/*

      - name: Prepare code
        shell: bash
        working-directory: ${{github.workspace}}/BUILD
        run: |
          ls -l ${HOME}/bin/
          export PATH=${HOME}/bin:$PATH
          mkdir -p src/lxr
          ./mk_cpp.sh

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/BUILD
        # Note the current convention is to use the -S and -B options here to specify source 
        # and build directories, but this is only available with CMake 3.13 and higher.  
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: |
          cmake --fresh -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE .

      - name: Build
        working-directory: ${{github.workspace}}/BUILD
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/BUILD
        shell: bash
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        #run: ctest -C $BUILD_TYPE
        run: ./ut.sh

      - name: Package
        working-directory: ${{github.workspace}}/BUILD
        shell: bash
        run: cpack

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with: 
          name: compiled-code
          path: BUILD/elykseer-crypto_*.tar.gz
